name: tox
on: [push, pull_request]
jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: pip install discord.py tox
      - run: tox -e py
        env:
          PYPRESENCE_CLIENT_ID: ${{ github.PYPRESENCE_CLIENT_ID }}

